In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from rbclib import RBCPath

In [2]:
# Paths
rbcdata_path = Path('/home/jovyan/shared/data/RBC')
train_filepath = rbcdata_path / 'train_participants.tsv'
test_filepath = rbcdata_path / 'test_participants.tsv'

# Load the PNC participants TSV files...
with train_filepath.open('r') as f:
    train_data = pd.read_csv(f, sep='\t')
with test_filepath.open('r') as f:
    test_data = pd.read_csv(f, sep='\t')

# We can also concatenate the two datasets into a single dataset of all study participants:
all_data = pd.concat([train_data, test_data])

# Display the full dataframe:
all_data

participant_id study study_site session_id  wave        age     sex  \
0        1000393599   PNC       PNC1       PNC1     1  15.583333    Male   
1        1001970838   PNC       PNC1       PNC1     1  17.833333    Male   
2        1007995238   PNC       PNC1       PNC1     1  13.750000  Female   
3        1011497669   PNC       PNC1       PNC1     1  16.666667    Male   
4        1017092387   PNC       PNC1       PNC1     1  18.666667  Female   
..              ...   ...        ...        ...   ...        ...     ...   
529       969649154   PNC       PNC1       PNC1     1  12.333333    Male   
530       970890500   PNC       PNC1       PNC1     1  18.166667  Female   
531       975856179   PNC       PNC1       PNC1     1  11.000000    Male   
532       984757368   PNC       PNC1       PNC1     1  13.416667    Male   
533       987544292   PNC       PNC1       PNC1     1  18.416667  Female   

      race               ethnicity    bmi handedness participant_education  \
0    Black  not Hispanic or Latino  22.15      Right             9th Grade   
1    Other      Hispanic or Latino  23.98      Right            11th Grade   
2    Other  not Hispanic or Latino  23.77      Right             6th Grade   
3    White  not Hispanic or Latino  29.68      Right             9th Grade   
4    Black  not Hispanic or Latino  23.24      Right            11th Grade   
..     ...                     ...    ...        ...                   ...   
529  White  not Hispanic or Latino  17.38      Right             5th Grade   
530  White  not Hispanic or Latino  30.89      Right            11th Grade   
531  White  not Hispanic or Latino  15.67      Right             4th Grade   
532  Black  not Hispanic or Latino  16.66      Right             5th Grade   
533  White  not Hispanic or Latino    NaN      Right            11th Grade   

     parent_1_education  parent_2_education  p_factor  \
0      Complete primary  Complete secondary  0.589907   
1     Complete tertiary   Complete tertiary -0.659061   
2     Complete tertiary    Complete primary -1.608375   
3     Complete tertiary   Complete tertiary -1.233807   
4      Complete primary    Complete primary -0.923100   
..                  ...                 ...       ...   
529   Complete tertiary  Complete secondary       NaN   
530  Complete secondary  Complete secondary       NaN   
531    Complete primary  Complete secondary       NaN   
532    Complete primary                 NaN       NaN   
533  Complete secondary    Complete primary       NaN   

     internalizing_mcelroy_harmonized_all_samples  \
0                                       -0.449373   
1                                        0.531072   
2                                       -0.744118   
3                                       -0.896835   
4                                       -0.313455   
..                                            ...   
529                                     -0.148520   
530                                      0.993806   
531                                     -1.026645   
532                                      0.360029   
533                                      0.399735   

     externalizing_mcelroy_harmonized_all_samples  \
0                                       -0.630780   
1                                        0.392751   
2                                       -0.314187   
3                                       -0.449099   
4                                        2.204168   
..                                            ...   
529                                      0.556444   
530                                      1.578177   
531                                     -0.582212   
532                                     -0.515655   
533                                     -0.490472   

     attention_mcelroy_harmonized_all_samples  cubids_acquisition_group  
0                                   -1.842178                         1  
1                                    0.190706   

In [3]:
# Load function for brain structures (FreeSurfer SurfaceStats)
def load_fsdata(participant_id, local_cache_dir=(Path.home() / 'cache')):
    if local_cache_dir is not None:
        local_cache_dir = Path(local_cache_dir)
        local_cache_dir.mkdir(exist_ok=True)
    pnc_freesurfer_path = RBCPath('rbc://PNC_FreeSurfer/freesurfer', local_cache_dir=local_cache_dir)
    participant_path = pnc_freesurfer_path / f'sub-{participant_id}'
    tsv_path = participant_path / f'sub-{participant_id}_regionsurfacestats.tsv'
    with tsv_path.open('r') as f:
        data = pd.read_csv(f, sep='\t')
    return data

In [4]:
from ipywidgets import IntProgress
from IPython.display import display 

In [5]:
# Collect aparc features for each participant
all_vars = {'participant_id': [], 'p_factor': []}
progress = IntProgress(min=0, max=len(all_data))
display(progress)

all_records = []
for (ii, row) in all_data.iterrows():
    participant_id = row['participant_id']
    p_factor = row.get('p_factor', np.nan)
    try:
        data = load_fsdata(participant_id)
        if 'atlas' in data.columns:
            data = data[data['atlas'] == 'aparc']
        else:
            continue

        record = {'participant_id': participant_id, 'p_factor': p_factor}

        for struct_name in data['StructName'].unique():
            row_mask = (data['StructName'] == struct_name)
            for metric in ['SurfArea', 'GrayVol', 'ThickAvg']:
                if metric in data.columns:
                    values = data.loc[row_mask, metric]
                    if not values.empty:
                        value = values.sum() if metric != 'ThickAvg' else values.mean()
                        record[f"{struct_name}_{metric}"] = value

        all_records.append(record)

    except FileNotFoundError:
        continue
    progress.value += 1

IntProgress(value=0, max=1601)

In [6]:
all_vars = pd.DataFrame(all_records)

train_vars = all_vars[~np.isnan(all_vars['p_factor'])]
test_vars = all_vars[np.isnan(all_vars['p_factor'])]

all_vars

participant_id  p_factor  bankssts_SurfArea  bankssts_GrayVol  \
0         1000393599  0.589907               2024              5272   
1         1001970838 -0.659061               2003              5122   
2         1007995238 -1.608375               2138              5765   
3         1011497669 -1.233807               2086              5387   
4         1017092387 -0.923100               1753              4499   
...              ...       ...                ...               ...   
1587       969649154       NaN               2190              5636   
1588       970890500       NaN               1609              3906   
1589       975856179       NaN               2488              6656   
1590       984757368       NaN               2395              6443   
1591       987544292       NaN               2007              5458   

      bankssts_ThickAvg  caudalanteriorcingulate_SurfArea  \
0                2.8115                              1186   
1                2.6610                              1120   
2                2.8985                              1368   
3                2.6495                              1564   
4                2.6755                              1259   
...                 ...                               ...   
1587             2.7400                              1554   
1588             2.6330                               804   
1589             2.8785                              1563   
1590             2.7775                              1054   
1591             2.8530                              1465   

      caudalanteriorcingulate_GrayVol  caudalanteriorcingulate_ThickAvg  \
0                                4002                            2.8760   
1                                2993                            2.6140   
2                                4447                            2.7920   
3                                5125                            2.7680   
4                                4348                            2.8755   
...                               ...                               ...   
1587                             4868                            2.8835   
1588                             2875                            3.3575   
1589                             5023                            2.8210   
1590                             2819                            2.5405   
1591                             4933                            2.7975   

      caudalmiddlefrontal_SurfArea  caudalmiddlefrontal_GrayVol  ...  \
0                             4332                        13053  ...   
1                             3953                        11624  ...   
2                             4306                        13952  ...   
3                             4451                        14348  ...   
4                             4183                        13355  ...   
...                            ...                          ...  ...   
1587                          5386                        15811  ...   
1588                          4061                        13061  ...   
1589                          5528                        18063  ...   
1590                          5182                        15640  ...   
1591                          4469                        13587  ...   

      frontalpole_ThickAvg  temporalpole_SurfArea  temporalpole_GrayVol  \
0                   3.1460                   1001                  5852   
1                   2.9440                    772                  4282   
2                   2.6575                    846                  5064   
3                   2.8965                    754                  4401   
4                   2.9625                    945                  5285   
...                    ...                    ...                   ...   
1587                2.6820                    915                  5029   
1588                2.6760                    741     

In [7]:
# Correlation
missing_thresh = 0.3
missing_frac = train_vars.isna().mean()
feature_cols = missing_frac[(missing_frac < missing_thresh)].index.difference(['participant_id', 'p_factor'])
corr = train_vars[feature_cols.tolist() + ['p_factor']].corr()
top_corr = corr['p_factor'].drop('p_factor').abs().sort_values(ascending=False).head(15)
top_corr

precuneus_ThickAvg              0.193352
superiorparietal_GrayVol        0.190804
precuneus_GrayVol               0.190091
rostralmiddlefrontal_GrayVol    0.181274
postcentral_GrayVol             0.176104
paracentral_ThickAvg            0.176056
superiorfrontal_GrayVol         0.173695
posteriorcingulate_GrayVol      0.168816
postcentral_ThickAvg            0.165617
precentral_GrayVol              0.164963
inferiorparietal_GrayVol        0.161817
bankssts_ThickAvg               0.160552
caudalmiddlefrontal_GrayVol     0.159332
cuneus_ThickAvg                 0.158056
lateralorbitofrontal_GrayVol    0.156392
Name: p_factor, dtype: float64

In [8]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import joblib

In [9]:
# ML Pipeline with ElasticNet 
from sklearn.linear_model import ElasticNetCV

param_grid = {
    'model__alpha': [0.001, 0.01, 0.1, 1.0, 10.0],
    'model__l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9]
}

pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler()),
    ('model', ElasticNetCV(
        l1_ratio=[0.1, 0.3, 0.5, 0.7, 0.9],
        alphas=[0.001, 0.01, 0.1, 1.0, 10.0],
        cv=5,
        max_iter=10000,
        random_state=42
    ))
])

# Drop rows with missing values for model training
X = train_vars[feature_cols.tolist()]
#X = X.dropna()
y = train_vars['p_factor']

pipeline.fit(X, y)

print("Best alpha:", pipeline.named_steps['model'].alpha_)
print("Best l1_ratio:", pipeline.named_steps['model'].l1_ratio_)

# Mean R² score across folds 
mean_r2 = pipeline.named_steps['model'].mse_path_.mean(axis=1)
print("Mean MSEs:", mean_r2)

Best alpha: 0.1
Best l1_ratio: 0.3
Mean MSEs: [[0.87416538 0.96007875 0.80520173 0.8238343  0.85075443]
 [0.87304279 0.95934031 0.80181027 0.82797947 0.85039408]
 [0.87234875 0.95800649 0.79973502 0.82876898 0.84815405]
 [0.87209664 0.95742954 0.79857729 0.83026935 0.84758791]
 [0.87195371 0.95722843 0.79786799 0.83204081 0.84670892]]


In [10]:
# Optional
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)

print(f'Final R²: {r2_score(y_test, y_pred):.3f}')
print(f'MAE: {mean_absolute_error(y_test, y_pred):.3f}')
print(f'RMSE: {np.sqrt(mean_squared_error(y_test, y_pred)):.3f}')

Final R²: 0.030
MAE: 0.769
RMSE: 0.925


In [11]:
# Predict on test data
X_final = test_vars[X.columns]
test_okrows = np.all(~np.isnan(X_final.values), axis=1)
X_valid = X_final.loc[test_okrows]
predictions = pipeline.predict(X_valid)

# Apply predictions to subset of test_vars
pred_ids = test_vars.loc[test_okrows, 'participant_id']
results = pd.DataFrame({
    'participant_id': pred_ids,
    'p_factor_pred': predictions
})

test_data.loc[test_data['participant_id'].isin(pred_ids), 'p_factor'] = predictions

group_name = 'miniproj-group4'  
Path("results").mkdir(parents=True, exist_ok=True)
test_data.to_csv(f'results/{group_name}.tsv', sep='\t', index=False)